### ISSUE TITLE
o rly?

### ISSUE THREAD

**Issue by fabiocarneiro** [netojoaobatista/order-service#1]
![ohgodwhy?](https://weekendapologies.files.wordpress.com/2012/08/meme-angry_00277833.jpg)

**Comment by netojoaobatista** [comment]
Qual o problema, @fabiocarneiro?

**Comment by fabiocarneiro** [comment]
public $status? Cade o encapsulamento? Cade o comportamento?

**Comment by netojoaobatista** [comment]
São estruturas de dados, velhinho. Não são "_objetos_".

Dica de leitura: http://blog.8thlight.com/uncle-bob/2013/10/01/Dance-You-Imps.html

;)

**Comment by fabiocarneiro** [comment]
>  So they invented reasons. Reasons like: It's a closer way to model the real world! (What manager could say no to that?)

É a mesma coisa que dizer que o comportamento não pode ser no domain model porque não se parece com o "mundo real".

> An object is not a data structure. Repeat after me: An Object Is Not A Data Structure. OK, you keep repeating that while I keep talking.
> 
> An object is not a data structure. In fact, if you are the consumer of an object, you aren't allowed to see any data that might be inside it. And, in fact, the object might have no data inside it at all.
> 
> What do you see when you look at an object from the outside? **You see methods! You don't see any data; because the data (if any) is kept private**. All you are allowed to see, from the outside looking in, are methods. So, from the outside looking in, an object is an abstraction of **behavior**, not an abstraction of data

Preste atenção no negrito. Se você não pode ver dados, como quer atualizar um status de fora do domain model?

> So, designers, feel free to use ORMs to bring data structures from the disk (the disk? You still using one?) into memory. But please don't think of those data structures as your business objects.

Você ainda pode trazer os seus objetos (estruturas) do banco de dados, mas não pense neles como seus domain models. 

Isso que você fez é perfeitamente válido como exemplo de data structure, mas não pode nunca ser um exemplo de Domain Driven Design porque você nem ao menos está usando domain model.

**Comment by netojoaobatista** [comment]
Separei a responsabilidade - e comportamento - de validação, nos `OrderRepository` e `OrderPolicy`. A decisão de design foi tomada para que os clients do domínio utilizassem a interface do `OrderService` para consumir o `Order`. Se observar, os participantes externos ao domínio não lidam com o `Order`.

**Comment by fabiocarneiro** [comment]
Domain model certo? 

Como você quer colocar o comportamento do seu domain na service layer? Você ta modelando um data structure, colocando um comportamento em um lugar separado, e chamando isso de domain driven design.

**Comment by netojoaobatista** [comment]
Por isso tenho o `OrderService`, que consome `OrderRepository` que consome `OrderPolicy`.

**Comment by fabiocarneiro** [comment]
Você ta achando que a sua Application Service Layer faz parte do seu domain. Só que não.

**Comment by netojoaobatista** [comment]
Isso não é uma Application Service Layer. É um Domain Service que consome um Repository.

**Comment by fabiocarneiro** [comment]
E esse anemic model? Você vai deixar alguem acessar o seu repositório fora do seu "Domain Service Layer" e alterar a propriedade diretamente `$order->status =  1`? 

Dica de leitura: http://verraes.net/2013/04/crud-is-an-anti-pattern/

**Comment by netojoaobatista** [comment]
Por isso tenho o `OrderPolicy`.

Talvez você tenha caído de paraquedas aqui e, por isso, não tenha ideia do que está acontecendo. Veja essa thread: [Opinião sobre Design](https://www.facebook.com/groups/nao.tem.biscoito/permalink/10155449833805160/). Depois de tê-la visto, veja a issue #2.

Sobre sua dica de leitura, lerei.

**Comment by fabiocarneiro** [comment]
Não cai de paraquedas, já li ambas.

**Comment by netojoaobatista** [comment]
Se você leu, então não sei o que estamos discutindo aqui. O repositório foi criado para que as pessoas fizessem PR com suas sugestões. Se você não tem uma sugestão nem um PR, então estamos perdendo tempo aqui.

**Comment by fabiocarneiro** [comment]
Estavamos discutindo o fato do seu anemic model ser uma estrutura de dados. Estavamos discutindo o fato do seu anemic model não expressar nenhum comportamento. Então você simplesmente achou que não possuia mais argumentos e fechou a issue.

Eu lhe sugeri uma leitura, logo é uma sugestão.

Engraçado como a issue #2 também não é uma pull request e continua aberta.

**Comment by netojoaobatista** [comment]
Por que na issue #2 há uma sugestão de fato.

Tratei as entidades como estruturas de dados, porque é o que são. Essa issue foi fechada porque não traz um benefício para o repositório. A issue #2 tem uma proposta para o rumo do código. Você tem apenas uma opinião.

**Comment by fabiocarneiro** [comment]
Eu dei uma sugestão de leitura, e provavelmente daria outras. Mas como você considera apenas opnião, vou guardar a minha e observar o resultado final.

Abraço

**Comment by netojoaobatista** [comment]
Mas é o que é, @fabiocarneiro, apenas uma opinião. Eu dei a minha, você deu a sua. A diferença é que a minha está acompanhada de um código. A sua é só texto e uma figurinha no primeiro comentário.

Quer que sua opinião seja considerada? Faça um PR - ou faça como o Pascutti e abra uma issue útil, que possa realmente afetar o rumo do código. Porque da forma como está nesse instante, é uma opinião inútil que só nos faz perder tempo discutindo.
